---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13666.
--- DateTime: 2023/1/1 11:22
---

-- 1.参数列表 优惠券id、
-- 用户id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId =ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--库存
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
--用户是否下单
if(redis.call('sismember',orderKey,userId)==1)then
    return 2
end

--扣库存
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
-- 向stream.order队列中添加消息
redis.call('xadd','stream.order','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0
