---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13666.
--- DateTime: 2022/12/27 16:37
---

--锁的KEY
local key = KEYS[1]
local threadId = ARGV[1]
local id = redis.call('get',key)
if(id==threadId)
then
    return redis.call('delete',key)
end
return 0