---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13666.
--- DateTime: 2023/1/3 19:04
---

-- 判断 锁的标识是否是自己的
if (redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end

-- 不是自己的标识
return 0;